
export const TRANSLATIONS = {
  en: {
    welcome: 'Welcome, ',
    terminalActive: 'Personal Travel Terminal Active.',
    manualBooking: 'Journey Builder',
    autoBooking: 'AI Smart Plan',
    nodeTracking: 'Node Tracking',
    weatherTitle: 'Environment',
    forecast: 'Forecast',
    live: 'Live',
    gateInfo: 'GATE INFO',
    onTime: 'ON TIME',
    language: 'Language',
    itineraryBenchmarks: 'Itinerary Benchmarks',
    pricePaid: 'Price Paid',
    priceBenchmarking: 'Price Benchmarking',
    saved: 'Saved',
    indianJourneys: 'Indian Journeys',
    syncWidgets: 'Tap to sync widgets',
    flightDetails: 'FLIGHT DETAILS',
    flyingFrom: 'Flying From',
    destination: 'Destination',
    originCity: 'Origin City',
    targetCity: 'Target City',
    multiCityHint: 'Destinations (separated by comma)',
    departureDate: 'Departure Date',
    returnDate: 'Return Date',
    timeSlot: 'Time Slot',
    selectSeatMap: 'Select Seat Map',
    hotelPref: 'Hotel Tier',
    checkin: 'Check-In',
    checkout: 'Check-Out',
    rooms: 'Rooms',
    roomType: 'Room Type',
    cabSelection: 'CAB SELECTION',
    pickup: 'Pickup',
    dropoff: 'Dropoff',
    pickupLoc: 'Pickup location',
    dropoffLoc: 'Dropoff location',
    totalBurn: 'Total Estimated Burn',
    pay: 'Confirm & Lock',
    seatMapping: 'Seat Mapping',
    confirmSeats: 'Confirm Seats',
    upcoming: 'Active Nodes',
    valueTransferred: 'Value Transferred',
    cancel: 'Cancel Node',
    rebook: 'Modify Node',
    restoreNode: 'RESTORE NODE',
    syncBuddy: 'Sync with Buddy...',
    terminateSync: 'Terminate Sync',
    signIn: 'Launch Terminal',
    signUp: 'Join Node',
    payment: 'Payment Terminal',
    payAmount: 'Pay Amount',
    authorizeSync: 'Authorize Sync',
    oneway: 'One Way',
    round: 'Round Trip',
    multi: 'Multi-City',
    budgetLabel: 'Journey Budget',
    howManyPeople: 'How many people are traveling?',
    tripTypeQ: 'What is your trip type?',
    howManyCities: 'How many cities in multi-city?',
    whichCities: 'Enter city names (comma separated)',
    gateStable: 'GATE STABLE',
    gateUnstable: 'UNSTABLE',
    gateChanged: 'CHANGED',
    people: 'People'
  },
  te: {
    welcome: 'స్వాగతం, ',
    terminalActive: 'పర్సనల్ ట్రావెల్ టెర్మినల్ యాక్టివ్‌గా ఉంది.',
    manualBooking: 'జర్నీ బిల్డర్',
    autoBooking: 'AI స్మార్ట్ ప్లాన్',
    nodeTracking: 'నోడ్ ట్రాకింగ్',
    weatherTitle: 'వాతావరణం',
    forecast: 'భవిష్యత్తు సూచన',
    live: 'లైవ్',
    gateInfo: 'గేట్ సమాచారం',
    onTime: 'సమయానికి',
    language: 'భాష',
    itineraryBenchmarks: 'ప్రయాణ బెంచ్‌మార్క్‌లు',
    pricePaid: 'చెల్లించిన ధర',
    priceBenchmarking: 'ధర బెంచ్ మార్కింగ్',
    saved: 'ఆదా చేయబడింది',
    indianJourneys: 'భారతీయ ప్రయాణాలు',
    syncWidgets: 'విడ్జెట్‌లను సింక్ చేయడానికి ట్యాప్ చేయండి',
    flightDetails: 'ఫ్లైట్ వివరాలు',
    flyingFrom: 'ఎక్కడి నుండి',
    destination: 'గమ్యస్థానం',
    originCity: 'ప్రారంభ నగరం',
    targetCity: 'లక్ష్య నగరం',
    multiCityHint: 'గమ్యస్థానాలు (కామాలతో వేరు చేయండి)',
    departureDate: 'ప్రయాణ తేదీ',
    returnDate: 'తిరుగు ప్రయాణ తేదీ',
    timeSlot: 'సమయ స్లాట్',
    selectSeatMap: 'సీట్ మ్యాప్‌ను ఎంచుకోండి',
    hotelPref: 'హోటల్ శ్రేణి',
    checkin: 'చెక్-ఇన్',
    checkout: 'చెక్-అవుట్',
    rooms: 'గదులు',
    roomType: 'గది రకం',
    cabSelection: 'క్యాబ్ ఎంపిక',
    pickup: 'పికప్',
    dropoff: 'డ్రాప్‌ఆఫ్',
    pickupLoc: 'పికప్ స్థానం',
    dropoffLoc: 'డ్రాప్‌ఆఫ్ స్థానం',
    totalBurn: 'మొత్తం అంచనా వ్యయం',
    pay: 'నిర్ధారించు & లాక్ చేయి',
    seatMapping: 'సీట్ మ్యాపింగ్',
    confirmSeats: 'సీట్లను నిర్ధారించండి',
    upcoming: 'యాక్టివ్ నోడ్స్',
    valueTransferred: 'బదిలీ చేయబడిన విలువ',
    cancel: 'నోడ్‌ని రద్దు చేయి',
    rebook: 'నోడ్‌ని మార్చు',
    restoreNode: 'నోడ్‌ని పునరుద్ధరించు',
    syncBuddy: 'బడ్డీతో సింక్ చేయండి...',
    terminateSync: 'సింక్‌ని ముగించు',
    signIn: 'లాంచ్ టెర్మినల్',
    signUp: 'నోడ్‌లో చేరండి',
    payment: 'చెల్లింపు టెర్మినల్',
    payAmount: 'మొత్తం చెల్లించండి',
    authorizeSync: 'సింక్‌ని అనుమతించు',
    oneway: 'ఒక వైపు',
    round: 'రౌండ్ ట్రిప్',
    multi: 'మల్టీ-సిటీ',
    budgetLabel: 'జర్నీ బడ్జెట్',
    howManyPeople: 'ఎంత మంది ప్రయాణిస్తున్నారు?',
    tripTypeQ: 'మీ ట్రిప్ రకం ఏమిటి?',
    howManyCities: 'మల్టీ-సిటీలో ఎన్ని నగరాలు?',
    whichCities: 'నగర పేర్లు నమోదు చేయండి (కామాలతో వేరు చేయండి)',
    gateStable: 'గేట్ స్థిరంగా ఉంది',
    gateUnstable: 'అస్థిరంగా ఉంది',
    gateChanged: 'మారబడింది',
    people: 'ప్రజలు'
  },
  hi: {
    welcome: 'स्वागत है, ',
    terminalActive: 'व्यक्तिगत यात्रा टर्मिनल सक्रिय है।',
    manualBooking: 'यात्रा बिल्डर',
    autoBooking: 'AI स्मार्ट योजना',
    nodeTracking: 'नोड ट्रैकिंग',
    weatherTitle: 'वातावरण',
    forecast: 'पूर्वानुमान',
    live: 'लाइव',
    gateInfo: 'गेट की जानकारी',
    onTime: 'समय पर',
    language: 'भाषा',
    itineraryBenchmarks: 'यात्रा बेंचमार्क',
    pricePaid: 'भुगतान की गई राशि',
    priceBenchmarking: 'मूल्य बेंचमार्किंग',
    saved: 'बचत',
    indianJourneys: 'भारतीय यात्राएं',
    syncWidgets: 'विजेट सिंक करने के लिए टैप करें',
    flightDetails: 'उड़ान का विवरण',
    flyingFrom: 'कहाँ से',
    destination: 'गंतव्य',
    originCity: 'प्रस्थान शहर',
    targetCity: 'लक्ष्य शहर',
    multiCityHint: 'गंतव्य (कॉमा द्वारा अलग)',
    departureDate: 'प्रस्थान तिथि',
    returnDate: 'वापसी तिथि',
    timeSlot: 'टाइम स्लॉट',
    selectSeatMap: 'सीट मैप चुनें',
    hotelPref: 'होटल स्तर',
    checkin: 'चेक-इन',
    checkout: 'चेक-आउट',
    rooms: 'कमरे',
    roomType: 'कमरे का प्रकार',
    cabSelection: 'कैब चयन',
    pickup: 'पिकअप',
    dropoff: 'ड्रॉपऑफ',
    pickupLoc: 'पिकअप स्थान',
    dropoffLoc: 'ड्रॉपऑफ स्थान',
    totalBurn: 'कुल अनुमानित खर्च',
    pay: 'पुष्टि और लॉक करें',
    seatMapping: 'सीट मैपिंग',
    confirmSeats: 'सीटें सुरक्षित करें',
    upcoming: 'सक्रिय नोड्स',
    valueTransferred: 'स्थानांतरित मूल्य',
    cancel: 'नोड रद्द करें',
    rebook: 'नोड बदलें',
    restoreNode: 'नोड बहाल करें',
    syncBuddy: 'बडी के साथ सिंक करें...',
    terminateSync: 'सिंक समाप्त करें',
    signIn: 'टर्मिनल लॉन्च करें',
    signUp: 'नोड से जुड़ें',
    payment: 'भुगतान टर्मिनल',
    payAmount: 'भुगतान राशि',
    authorizeSync: 'सिंक अधिकृत करें',
    oneway: 'एक तरफ',
    round: 'राउंड ट्रिप',
    multi: 'मल्टी-सिटी',
    budgetLabel: 'यात्रा बजट',
    howManyPeople: 'कितने लोग यात्रा कर रहे हैं?',
    tripTypeQ: 'आपकी यात्रा का प्रकार क्या है?',
    howManyCities: 'मल्टी-सिटी में कितने शहर हैं?',
    whichCities: 'शहरों के नाम दर्ज करें (कॉमा द्वारा अलग)',
    gateStable: 'गेट स्थिर है',
    gateUnstable: 'अस्थिर',
    gateChanged: 'बदला गया',
    people: 'लोग'
  }
};
