
export const TRANSLATIONS = {
  en: {
    welcome: 'Welcome, ',
    subtitle: 'SMART INDIAN JOURNEYS',
    home: 'Home',
    chat: 'Buddy',
    booking: 'Trips',
    profile: 'Profile',
    signIn: 'Launch Terminal',
    signUp: 'Join Node',
    email: 'Terminal ID',
    password: 'Access Code',
    planTrip: 'New Journey',
    manualBooking: 'Journey Builder',
    autoBooking: 'AI Smart Plan',
    weatherTitle: 'Environment',
    budgetTitle: 'Budget Pulse',
    language: 'Language',
    theme: 'Theme',
    history: 'History',
    upcoming: 'Active Nodes',
    cancel: 'Cancel Node',
    rebook: 'Modify Node',
    rebookingTitle: 'Node Update',
    fareDiff: 'Fare Difference',
    confirmUpdate: 'Update Node',
    selectCity: 'Select Target Node',
    origin: 'Flying From',
    checkin: 'Check-in Date',
    checkout: 'Check-out Date',
    budgetLabel: 'Journey Budget',
    travelersLabel: 'Travelers',
    tripType: 'Trip Type',
    oneway: 'One Way',
    round: 'Round Trip',
    multi: 'Multi-City',
    prefTime: 'Time Slot',
    classLabel: 'Experience Class',
    hotelPref: 'Hotel Tier',
    economy: 'Economy',
    premiumEco: 'Premium Eco',
    business: 'Business',
    first: 'First Class',
    budgetTier: 'Budget',
    standardTier: 'Standard',
    premiumTier: 'Premium',
    luxuryTier: 'Luxury',
    heritage: 'Heritage',
    food: 'Food',
    shopping: 'Shopping',
    nature: 'Nature',
    experiences: 'Experiences',
    bestTime: 'Best Time',
    localTip: 'Local Tip',
    all: 'All Nodes',
    pay: 'Confirm & Lock',
    searching: 'Mapping Nodes...',
    summary: 'Node Summary',
    details: 'Details',
    bookNow: 'Book Now',
    reviews: 'Reviews',
    ratingBreakdown: 'Rating Breakdown',
    payment: 'Payment Terminal',
    selectPayment: 'Select Payment Method',
    upi: 'UPI',
    cards: 'Cards',
    netbanking: 'Net Banking',
    upiPlaceholder: 'Enter UPI ID (e.g. name@bank)',
    cardNumber: 'Card Number',
    cardHolder: 'Card Holder Name',
    expiry: 'Expiry Date',
    cvv: 'CVV',
    payAmount: 'Pay Amount',
    securePayment: 'Secure Encryption Active',
    paymentSuccess: 'Payment Successful',
    paymentFailed: 'Payment Failed',
    roomType: 'Room Type',
    rooms: 'Rooms',
    guests: 'Number of Guests',
    standard: 'Standard',
    deluxe: 'Deluxe',
    suite: 'Executive Suite',
    presidential: 'Presidential',
    cabType: 'Cab Type',
    pickup: 'Pickup Point',
    dropoff: 'Drop-off Point',
    auto: 'Auto',
    bike: 'Bike',
    sedan: 'Sedan',
    suv: 'SUV',
    luxuryCab: 'Luxury',
    diet: 'Dietary Choice',
    veg: 'Vegetarian',
    nonveg: 'Non-Vegetarian',
    low: 'Budget Friendly',
    medium: 'Value for Money',
    high: 'Luxury / Premium'
  },
  te: {
    welcome: 'స్వాగతం, ',
    subtitle: 'స్మార్ట్ ఇండియన్ జర్నీస్',
    home: 'హోమ్',
    chat: 'బడ్డీ',
    booking: 'ప్రయాణాలు',
    profile: 'ప్రొఫైల్',
    signIn: 'లాంచ్ టెర్మినల్',
    signUp: 'నోడ్‌లో చేరండి',
    email: 'టెర్మినల్ ఐడి',
    password: 'యాక్సెస్ కోడ్',
    planTrip: 'కొత్త ప్రయాణం',
    manualBooking: 'జర్నీ బిల్డర్',
    autoBooking: 'AI స్మార్ట్ ప్లాన్',
    weatherTitle: 'వాతావరణం',
    budgetTitle: 'బడ్జెట్ పల్స్',
    language: 'భాష',
    theme: 'థీమ్',
    history: 'చరిత్ర',
    upcoming: 'యాక్టివ్ నోడ్స్',
    cancel: 'నోడ్‌ని రద్దు చేయి',
    rebook: 'నోడ్‌ని మార్చు',
    rebookingTitle: 'నోడ్ అప్‌డేట్',
    fareDiff: 'ధర వ్యత్యాసం',
    confirmUpdate: 'నోడ్ అప్‌డేట్ చేయి',
    selectCity: 'టార్గెట్ నోడ్ ఎంచుకోండి',
    origin: 'ఎక్కడి నుండి',
    checkin: 'చెక్-ఇన్ తేదీ',
    checkout: 'చెక్-అవుట్ తేదీ',
    budgetLabel: 'బడ్జెట్',
    travelersLabel: 'ప్రయాణికులు',
    tripType: 'ప్రయాణ రకం',
    oneway: 'ఒక వైపు',
    round: 'రాౌండ్ ట్రిప్',
    multi: 'మల్టీ-సిటీ',
    prefTime: 'సమయ స్లాట్',
    classLabel: 'అనుభవ తరగతి',
    hotelPref: 'హోటల్ శ్రేణి',
    economy: 'ఎకానమీ',
    premiumEco: 'ప్రీమియం ఎకో',
    business: 'బిజినెస్',
    first: 'ఫస్ట్ క్లాస్',
    budgetTier: 'బడ్జెట్',
    standardTier: 'స్టాండర్డ్',
    premiumTier: 'ప్రీమియం',
    luxuryTier: 'లగ్జరీ',
    heritage: 'వారసత్వం',
    food: 'ఆహారం',
    shopping: 'షాపింగ్',
    nature: 'ప్రకృతి',
    experiences: 'అనుభవాలు',
    bestTime: 'ఉత్తమ సమయం',
    localTip: 'స్థానిక చిట్కా',
    all: 'అన్ని నోడ్స్',
    pay: 'నిర్ధారించు & లాక్ చేయి',
    searching: 'నోడ్స్ మ్యాపింగ్...',
    summary: 'నోడ్ సారాంశం',
    details: 'వివరాలు',
    bookNow: 'ఇప్పుడే బుక్ చేయండి',
    reviews: 'సమీక్షలు',
    ratingBreakdown: 'రేటింగ్ బ్రేక్‌డౌన్',
    payment: 'చెల్లింపు',
    selectPayment: 'చెల్లింపు పద్ధతిని ఎంచుకోండి',
    upi: 'UPI',
    cards: 'కార్డులు',
    netbanking: 'నెట్ బ్యాంకింగ్',
    upiPlaceholder: 'UPI ID నమోదు చేయండి',
    cardNumber: 'కార్డ్ నంబర్',
    cardHolder: 'కార్డ్ హోల్డర్ పేరు',
    expiry: 'గడువు తేదీ',
    cvv: 'CVV',
    payAmount: 'మొత్తం చెల్లించండి',
    securePayment: 'సురక్షిత ఎన్‌క్రిప్షన్ యాక్టివ్',
    paymentSuccess: 'చెల్లింపు విజయవంతమైంది',
    paymentFailed: 'చెల్లింపు విఫలమైంది',
    roomType: 'గది రకం',
    rooms: 'గదుల సంఖ్య',
    guests: 'అతిథుల సంఖ్య',
    standard: 'స్టాండర్డ్',
    deluxe: 'డీలక్స్',
    suite: 'సూట్',
    presidential: 'ప్రెసిడెన్షియల్',
    cabType: 'క్యాబ్ రకం',
    pickup: 'పికప్ పాయింట్',
    dropoff: 'డ్రాప్-ఆఫ్ పాయింట్',
    auto: 'ఆటో రిక్షా',
    bike: 'బైక్ టాక్సీ',
    sedan: 'సెడాన్',
    suv: 'SUV',
    luxuryCab: 'లగ్జరీ సెడాన్',
    diet: 'ఆహార ప్రాధ్యాన్యత',
    veg: 'శాకాహారం',
    nonveg: 'మాంసాహారం',
    low: 'బడ్జెట్ స్నేహపూర్వక',
    medium: 'విలువైనది',
    high: 'లగ్జరీ / ప్రీమియం'
  },
  hi: {
    welcome: 'स्वागत है, ',
    subtitle: 'स्मार्ट इंडियन जर्नी',
    home: 'होम',
    chat: 'बडी',
    booking: 'यात्राएं',
    profile: 'प्रोफ़ाइल',
    signIn: 'टर्मिनल लॉन्च करें',
    signUp: 'नोड से जुड़ें',
    email: 'टर्मिनल आईडी',
    password: 'एक्सेस कोड',
    planTrip: 'नई यात्रा',
    manualBooking: 'यात्रा बिल्डर',
    autoBooking: 'AI स्मार्ट प्लान',
    weatherTitle: 'वातावरण',
    budgetTitle: 'बजट पल्स',
    language: 'भाषा',
    theme: 'थीम',
    history: 'इतिहास',
    upcoming: 'सक्रिय नोड्स',
    cancel: 'नोड रद्द करें',
    rebook: 'नोड बदलें',
    rebookingTitle: 'नोड अपडेट',
    fareDiff: 'किराया अंतर',
    confirmUpdate: 'नोड अपडेट करें',
    selectCity: 'लक्ष्य नोड चुनें',
    origin: 'कहां से',
    checkin: 'चेक-इन तिथि',
    checkout: 'चेक-आउट तिथि',
    budgetLabel: 'बजट',
    travelersLabel: 'यात्री',
    tripType: 'यात्रा प्रकार',
    oneway: 'एक तरफ',
    round: 'राउंड ट्रिप',
    multi: 'मल्टी-सिटी',
    prefTime: 'टाइम स्लॉट',
    classLabel: 'अनुभव श्रेणी',
    hotelPref: 'होटल स्तर',
    economy: 'इकोनॉमी',
    premiumEco: 'प्रीमियम इको',
    business: 'बिजनेस',
    first: 'प्रथम श्रेणी',
    budgetTier: 'बजट',
    standardTier: 'मानक',
    premiumTier: 'प्रीमियम',
    luxuryTier: 'लक्जरी',
    heritage: 'विरासत',
    food: 'भोजन',
    shopping: 'खरीदारी',
    nature: 'प्रकृति',
    experiences: 'अनुभव',
    bestTime: 'सबसे अच्छा समय',
    localTip: 'स्थानीय सलाह',
    all: 'सभी नोड्स',
    pay: 'पुष्टि और लॉक करें',
    searching: 'नोड्स मैपिंग...',
    summary: 'नोड सूपर्ण',
    details: 'विवरण',
    bookNow: 'अभी बुक करें',
    reviews: 'समीक्षाएं',
    ratingBreakdown: 'रेटिंग विवरण',
    payment: 'भुगतान',
    selectPayment: 'भुगतान विधि चुनें',
    upi: 'UPI',
    cards: 'कार्ड',
    netbanking: 'नेट बैंकिंग',
    upiPlaceholder: 'UPI ID दर्ज करें',
    cardNumber: 'कार्ड नंबर',
    cardHolder: 'कार्ड धारक का नाम',
    expiry: 'समाप्ति तिथि',
    cvv: 'CVV',
    payAmount: 'भुगतान राशि',
    securePayment: 'सुरक्षित एन्क्रिप्शन सक्रिय',
    paymentSuccess: 'भुगतान सफल',
    paymentFailed: 'भुगतान विफल',
    roomType: 'कमरे का प्रकार',
    rooms: 'कमरों की संख्या',
    guests: 'मेहमानों की संख्या',
    standard: 'मानक',
    deluxe: 'डीलक्स',
    suite: 'सुइट',
    presidential: 'प्रेसिडेंशियल',
    cabType: 'कैब का प्रकार',
    pickup: 'पिकअप पॉइंट',
    dropoff: 'ड्रॉप-ऑफ पॉइंट',
    auto: 'ऑटो रिक्शा',
    bike: 'बाइक टैक्सी',
    sedan: 'सेडान',
    suv: 'SUV',
    luxuryCab: 'लक्जरी सेडान',
    diet: 'आहार प्राथमिकता',
    veg: 'शाकाहारी',
    nonveg: 'मांसाहारी',
    low: 'बजट अनुकूल',
    medium: 'पैसों की कीमत',
    high: 'लक्जरी / प्रीमियम'
  }
};
